// cars.js — данные автомобилей BuyAuto Астана
// Сгенерировано из Excel-таблицы. Владельцы и залоги убраны как внутренняя информация.

const CARS = [
  {
    id: 1, brand: "Chevrolet", model: "Camaro", year: 2017, color: "Фиолетовый",
    mileage: 116000, engine: 2.0, fuel: "бензин", price: 14000000,
    photo: "photos/chevrolet_camaro_2017.jpg",
    condition: "Отличное",
    features: ["Бронепленка", "Спорткар"],
    description: "Легендарный американский маслкар. Дерзкий дизайн, мощный характер. Полностью покрыт бронепленкой. V4 Turbo, 275 л.с. Прямой впрыск, 6-ступенчатая АКПП. Идеальное состояние для любителей спортивных авто.",
    bodyType: "купе",
    drive: "задний",
    transmission: "АКПП",
    power: 275,
    seats: 4
  },
  {
    id: 2, brand: "GAC", model: "Trumpchi M8", year: 2024, color: "Белый",
    mileage: 23000, engine: 2.0, fuel: "бензин", price: 21500000,
    photo: "photos/gac_trumpchi_m8_2024.jpg",
    condition: "Отличное",
    features: ["Полный привод", "7 мест", "Вентиляция сидений", "Массаж сидений", "Климат-контроль", "Родной окрас", "Полная комплектация"],
    description: "Полноприводный бизнес-минивэн, технически полностью обслужен. 252 л.с., 7 мест, вентиляция/подогрев/массаж сидений, многозонный климат-контроль. 100% в родном окрасе. Полная комплектация.",
    bodyType: "минивэн",
    drive: "полный",
    transmission: "АКПП",
    power: 252,
    seats: 7
  },
  {
    id: 3, brand: "Hyundai", model: "Staria", year: 2022, color: "Серый",
    mileage: 44400, engine: 3.5, fuel: "бензин", price: 24000000,
    photo: "photos/hyundai_staria_2022.jpg",
    condition: "Максимальная комплектация",
    features: ["Дилерский", "На гарантии", "7 мест", "Люк", "Панорама", "Камера 360", "Зима/лето", "Бронепленка люкс"],
    description: "Дилерский автомобиль на гарантии с 1 ТО в подарок. Передний привод, 7 мест. Люкс-пакет бронепленки, шумоизоляция, люк, панорама, камера 360°, капитанские сиденья. Полностью обслужена. 100% в родном окрасе.",
    bodyType: "минивэн",
    drive: "передний",
    transmission: "АКПП",
    power: 272,
    seats: 7
  },
  {
    id: 4, brand: "Toyota", model: "Corolla", year: 2014, color: "Серый",
    mileage: 231000, engine: 1.6, fuel: "бензин", price: 6700000,
    photo: "photos/toyota_corolla_2014.jpg",
    condition: "Хорошее",
    features: ["Климат-контроль", "Подогрев сидений", "Зима/лето"],
    description: "Надёжная японская классика. 90% в родном окрасе. Комплект шин зима/лето. Климат-контроль, подогрев сидений. Без вложений, полностью обслужена. Чистый ухоженный салон. Двигатель 1.6 122 л.с.",
    bodyType: "седан",
    drive: "передний",
    transmission: "АКПП",
    power: 122,
    seats: 5
  },
  {
    id: 5, brand: "Hyundai", model: "Grandeur", year: 2020, color: "Тёмно-серый",
    mileage: null, engine: 2.5, fuel: "бензин", price: 13000000,
    photo: "photos/hyundai_grandeur_2020.jpg",
    condition: "Хорошее",
    features: ["Полный привод", "Зима/лето", "Полная комплектация"],
    description: "Представительский седан бизнес-класса. Полный привод, 2.5л, 180 л.с. Полная комплектация: кожаный салон, проекция на лобовое, вентиляция сидений. Комплект зима/лето в хорошем состоянии.",
    bodyType: "седан",
    drive: "полный",
    transmission: "АКПП",
    power: 180,
    seats: 5
  },
  {
    id: 6, brand: "Renault", model: "Arkana", year: 2021, color: "Серый",
    mileage: 86000, engine: 1.3, fuel: "бензин", price: 8500000,
    photo: "photos/renault_arkana_2021.jpg",
    condition: "Отличное",
    features: ["Полный привод", "Турбо", "Зима/лето", "Сигнализация Starline"],
    description: "Стильный кроссовер-купе. Полный привод, турбированный двигатель 1.3 150 л.с. Сигнализация Starline, комплект зима/лето. В отличном состоянии. Экономичный расход — 7–8 л на 100 км.",
    bodyType: "кроссовер",
    drive: "полный",
    transmission: "АКПП",
    power: 150,
    seats: 5
  },
  {
    id: 7, brand: "Volkswagen", model: "Polo", year: 2012, color: "Серый",
    mileage: 211800, engine: 1.6, fuel: "бензин", price: 4800000,
    photo: "photos/vw_polo_2012.jpg",
    condition: "Хорошее",
    features: ["Android-магнитола", "Камера заднего вида", "Без вложений"],
    description: "Классический немецкий хэтчбек. Полностью обслужен, без вложений — сел и поехал. Android-магнитола, камера заднего вида. Ухоженный салон, бережная эксплуатация. 1.6 105 л.с.",
    bodyType: "хэтчбек",
    drive: "передний",
    transmission: "АКПП",
    power: 105,
    seats: 5
  },
  {
    id: 8, brand: "Hyundai", model: "Elantra", year: 2024, color: "Белый",
    mileage: 40000, engine: 1.6, fuel: "бензин", price: 10900000,
    photo: "photos/hyundai_elantra_2024.jpg",
    condition: "Отличное",
    features: ["Дилерский", "Родной окрас", "Передний привод", "АКПП"],
    description: "Новый дилерский Hyundai Elantra 7-го поколения. Передний привод, АКПП. 1.6 123 л.с. Родной окрас, без касаний. Современный дизайн, мультимедия с Apple CarPlay/Android Auto.",
    bodyType: "седан",
    drive: "передний",
    transmission: "АКПП",
    power: 123,
    seats: 5
  },
  {
    id: 9, brand: "Changan", model: "Qiyuan A07", year: 2025, color: "Белый",
    mileage: 0, engine: 1.5, fuel: "гибрид", price: 13500000,
    photo: "photos/changan_qiyuan_a07_2025.jpg",
    condition: "Новый",
    features: ["Гибрид", "Запас хода 1200 км", "Премиальный лифтбек", "Тонировка", "Русификация в подарок"],
    description: "Премиальный гибридный лифтбек нового поколения. Запас хода до 1200 км! 1.5T PHEV гибрид. Комфортная комплектация, шины в комплекте, тонировка. Русификация в подарок. Технология умного управления энергией.",
    bodyType: "лифтбек",
    drive: "передний",
    transmission: "АКПП",
    power: 188,
    seats: 5
  },
  {
    id: 10, brand: "Changan", model: "CS75 Plus", year: 2025, color: "Серый",
    mileage: 9000, engine: 1.5, fuel: "бензин", price: 12800000,
    photo: "photos/changan_cs75plus_2025.jpg",
    condition: "Почти новый",
    features: ["Передний привод", "Родной окрас"],
    description: "Флагманский кроссовер Changan. Практически новый, пробег всего 9 000 км. 1.5T 188 л.с. Передний привод. 100% в родном окрасе. Современная мультимедиа, богатая комплектация.",
    bodyType: "кроссовер",
    drive: "передний",
    transmission: "АКПП",
    power: 188,
    seats: 5
  },
  {
    id: 11, brand: "Chevrolet", model: "Monza", year: 2023, color: "Белый",
    mileage: 11000, engine: 1.5, fuel: "бензин", price: 7800000,
    photo: "photos/chevrolet_monza_2023.jpg",
    condition: "Отличное",
    features: ["Зима/лето", "Автозапуск"],
    description: "Современный седан Chevrolet в отличном состоянии. Пробег 11 000 км, как новый. 1.5T 147 л.с. Автозапуск, зима/лето. Просторный салон, надёжная корейская сборка.",
    bodyType: "седан",
    drive: "передний",
    transmission: "АКПП",
    power: 147,
    seats: 5
  },
  {
    id: 12, brand: "BYD", model: "Destroyer 05", year: 2025, color: "Белый",
    mileage: 47, engine: 1.5, fuel: "гибрид", price: 8700000,
    photo: "photos/byd_destroyer05_2025.jpg",
    condition: "Новый",
    features: ["Гибрид", "Запас хода 1200 км", "ДВС 110 л.с.", "Расход 4-5 л"],
    description: "Гибридный седан BYD DM-i. Новый, пробег 47 км. Мощность ДВС 110 л.с. + электромотор. Запас хода до 1200 км. Средний расход 4–5 л на 100 км. Технология Blade Battery. Современный интерьер с большим экраном.",
    bodyType: "седан",
    drive: "передний",
    transmission: "АКПП",
    power: 218,
    seats: 5
  },
  {
    id: 13, brand: "Changan", model: "Qiyuan A07", year: 2025, color: "Чёрный",
    mileage: 30, engine: 1.5, fuel: "гибрид", price: 12800000,
    photo: "photos/changan_qiyuan_a07_black_2025.jpg",
    condition: "Новый",
    features: ["Новый", "Гибрид"],
    description: "Абсолютно новый Changan Qiyuan A07 в чёрном цвете. Пробег 30 км — с завода. Гибридная система, запас хода 1200 км. Технологичный интерьер, OTA-обновления.",
    bodyType: "лифтбек",
    drive: "передний",
    transmission: "АКПП",
    power: 188,
    seats: 5
  },
  {
    id: 14, brand: "Haval", model: "Jolion", year: 2024, color: "Белый",
    mileage: 30000, engine: 1.5, fuel: "бензин", price: 10400000,
    photo: "photos/haval_jolion_2024.jpg",
    condition: "Состояние нового авто",
    features: ["На гарантии", "Без вложений"],
    description: "Стильный китайский кроссовер. Как новый, ещё на гарантии. 1.5T 150 л.с. Без вложений. Современный дизайн, просторный салон, панорамная крыша, 360° камера в базе.",
    bodyType: "кроссовер",
    drive: "передний",
    transmission: "АКПП",
    power: 150,
    seats: 5
  },
  {
    id: 15, brand: "Toyota", model: "Veloz", year: 2023, color: "Серый",
    mileage: 33340, engine: 1.5, fuel: "бензин", price: 12500000,
    photo: "photos/toyota_veloz_2023.jpg",
    condition: "Отличное",
    features: ["7 мест", "Apple CarPlay", "Полная комплектация"],
    description: "Семейный минивэн Toyota Veloz. 7 мест, просторный багажник. 1.5 105 л.с. Полная комплектация: Apple CarPlay, климат-контроль, камера заднего вида, раздельный 2-й и 3-й ряд.",
    bodyType: "минивэн",
    drive: "передний",
    transmission: "АКПП",
    power: 105,
    seats: 7
  },
  {
    id: 16, brand: "Hyundai", model: "Veloster", year: 2013, color: "Оранжевый",
    mileage: 95000, engine: 1.6, fuel: "бензин", price: 6500000,
    photo: "photos/hyundai_veloster_2013.jpg",
    condition: "Отличное",
    features: ["Зима/лето", "Автозапуск", "Спорткар"],
    description: "Уникальный спортивный хэтчбек с нестандартными 3 дверями. Яркий оранжевый цвет. 1.6 GDI 140 л.с. Отличное состояние. Зима/лето, автозапуск. Редкий автомобиль в Казахстане.",
    bodyType: "хэтчбек",
    drive: "передний",
    transmission: "АКПП",
    power: 140,
    seats: 4
  },
  {
    id: 17, brand: "Hyundai", model: "Santa Fe", year: 2018, color: "Белый",
    mileage: 188000, engine: 2.4, fuel: "бензин", price: 13000000,
    photo: "photos/hyundai_santafe_2018.jpg",
    condition: "Хорошее",
    features: ["Передний привод", "90% родной окрас", "Зима/лето"],
    description: "Популярный семейный кроссовер. 2.4 188 л.с. Передний привод. 90% в родном окрасе. Зима/лето шины. Panorama, подогрев сидений, кожаный салон. Надёжный проверенный автомобиль.",
    bodyType: "кроссовер",
    drive: "передний",
    transmission: "АКПП",
    power: 188,
    seats: 5
  },
  {
    id: 18, brand: "Kia", model: "Sorento", year: 2021, color: "Серый",
    mileage: 137000, engine: 2.5, fuel: "бензин", price: 14900000,
    photo: "photos/kia_sorento_2021.jpg",
    condition: "Отличное",
    features: ["Полный привод", "Полностью обслужен", "5 мест", "85% родной окрас", "Зима/лето"],
    description: "Семейный кроссовер Kia Sorento 4-го поколения. Полный привод, 2.5 180 л.с. Предмаксимальная комплектация. 5 мест. Полностью обслужен, без вложений. Зима/лето. 85% в родном окрасе.",
    bodyType: "кроссовер",
    drive: "полный",
    transmission: "АКПП",
    power: 180,
    seats: 5
  },
  {
    id: 19, brand: "Kia", model: "Sportage", year: 2025, color: "Белый",
    mileage: 0, engine: 2.0, fuel: "бензин", price: 15500000,
    photo: "photos/kia_sportage_2025.jpg",
    condition: "Новый",
    features: ["Новый", "Дилерский", "5 лет гарантии", "5 ТО в подарок"],
    description: "Абсолютно новый Kia Sportage 5-го поколения. Дилерский авто, 5 лет гарантии и 5 ТО в подарок. Средняя комплектация. 2.0 150 л.с. Стильный дизайн, цифровая приборная панель, ADAS.",
    bodyType: "кроссовер",
    drive: "передний",
    transmission: "АКПП",
    power: 150,
    seats: 5
  },
  {
    id: 20, brand: "Hyundai", model: "Santa Fe", year: 2025, color: "Белый",
    mileage: 28000, engine: 2.5, fuel: "бензин", price: 21500000,
    photo: "photos/hyundai_santafe_2025.jpg",
    condition: "Состояние нового авто",
    features: ["Вся в родне", "Люкс пакет", "Бронепленка"],
    description: "Santa Fe 5-го поколения в максимальном исполнении. 2.5T 281 л.с. Полностью в родном окрасе. Люкс пакет, бронепленка. Самый современный Hyundai: Digital Key, BOSE аудио, вентиляция и массаж сидений, HUD.",
    bodyType: "кроссовер",
    drive: "передний",
    transmission: "АКПП",
    power: 281,
    seats: 5
  },
  {
    id: 21, brand: "Mercedes-Benz", model: "G63 AMG", year: 2013, color: "Чёрный",
    mileage: 142000, engine: 5.5, fuel: "бензин", price: 36000000,
    photo: "photos/mercedes_g63amg_2013.jpg",
    condition: "Легендарное состояние",
    features: ["Biturbo", "544 л.с.", "1 хозяин", "100% родной окрас", "Любые проверки"],
    description: "Легендарный Mercedes G63 AMG V8 Biturbo 544 л.с. Один хозяин, кристально чистая история. Кузов 100% в родном окрасе, включая бампера. Любые проверки. Символ статуса и внедорожных способностей.",
    bodyType: "внедорожник",
    drive: "полный",
    transmission: "АКПП",
    power: 544,
    seats: 5
  },
  {
    id: 22, brand: "Hyundai", model: "Tucson", year: 2017, color: "Чёрный",
    mileage: 92000, engine: 2.0, fuel: "бензин", price: 9500000,
    photo: "photos/hyundai_tucson_2017.jpg",
    condition: "Отличное",
    features: ["Полностью обслужен", "85% родной окрас", "Зима/лето", "Без вложений"],
    description: "Hyundai Tucson 3-го поколения. 2.0 150 л.с. Полностью обслужен, без вложений. 85% в родном окрасе. Зима/лето. Климат-контроль, камера заднего вида, подогрев сидений.",
    bodyType: "кроссовер",
    drive: "передний",
    transmission: "АКПП",
    power: 150,
    seats: 5
  },
  {
    id: 23, brand: "Hyundai", model: "Sonata", year: 2020, color: "Синий",
    mileage: 87000, engine: 2.0, fuel: "бензин", price: 12000000,
    photo: "photos/hyundai_sonata_2020.jpg",
    condition: "Отличное",
    features: ["Пригнан из Кореи", "Панорама", "Камера 360", "Светлая кожа", "Зима/лето"],
    description: "Hyundai Sonata DN8 пригнана из Кореи. Полная комплектация: панорамная крыша, проекция на лобовое, камера 360°, светлая кожа. Без вложений. Зима/лето.",
    bodyType: "седан",
    drive: "передний",
    transmission: "АКПП",
    power: 150,
    seats: 5
  },
  {
    id: 24, brand: "Toyota", model: "Camry", year: 2011, color: "Чёрный",
    mileage: 271000, engine: 2.5, fuel: "бензин", price: 7300000,
    photo: "photos/toyota_camry_2011.jpg",
    condition: "Хорошее",
    features: ["Японец", "АКПП", "Технически исправен"],
    description: "Легендарная Toyota Camry VII (XV50). Чистокровный японец, технически в хорошем состоянии. 2.5 181 л.с., АКПП. Неприхотливый и надёжный автомобиль с ресурсом 500 000+ км.",
    bodyType: "седан",
    drive: "передний",
    transmission: "АКПП",
    power: 181,
    seats: 5
  },
  {
    id: 25, brand: "KIA", model: "K7", year: 2015, color: "Тёмный",
    mileage: null, engine: 3.0, fuel: "бензин", price: 8000000,
    photo: "photos/kia_k7_2015.jpg",
    condition: "Хорошее",
    features: ["Полный привод", "Зима/лето", "Полная комплектация"],
    description: "Представительский седан KIA K7 с 3.0-литровым V6 270 л.с. Полный привод, полная комплектация. Комфортный и статусный автомобиль бизнес-класса. Зима/лето в хорошем состоянии.",
    bodyType: "седан",
    drive: "полный",
    transmission: "АКПП",
    power: 270,
    seats: 5
  },
  {
    id: 26, brand: "Mitsubishi", model: "Outlander", year: 2022, color: "Белый",
    mileage: 100000, engine: 2.0, fuel: "бензин", price: 11000000,
    photo: "photos/mitsubishi_outlander_2022.jpg",
    condition: "Отличное",
    features: ["Дилерский японец", "Передний привод", "100% родной окрас", "Подогрев руля", "Камера заднего вида", "Зима/лето"],
    description: "Дилерский Mitsubishi Outlander 2022. Передний привод, 2.0 150 л.с. Отличное состояние. Подогрев руля и сидений, камера заднего вида, 100% в родном окрасе. Зима/лето.",
    bodyType: "кроссовер",
    drive: "передний",
    transmission: "АКПП",
    power: 150,
    seats: 5
  },
  {
    id: 27, brand: "KIA", model: "Rio", year: 2018, color: "Белый",
    mileage: 103000, engine: 1.6, fuel: "бензин", price: 7800000,
    photo: "photos/kia_rio_2018.jpg",
    condition: "Хорошее",
    features: ["Передний привод", "Технически исправен"],
    description: "KIA Rio 4-го поколения — эталон надёжности в классе. 1.6 123 л.с. Передний привод, АКПП. Технически в хорошем состоянии. Экономичный, практичный городской автомобиль.",
    bodyType: "седан",
    drive: "передний",
    transmission: "АКПП",
    power: 123,
    seats: 5
  },
  {
    id: 28, brand: "Hyundai", model: "Elantra", year: 2022, color: "Серый",
    mileage: 102600, engine: 2.0, fuel: "бензин", price: 8900000,
    photo: "photos/hyundai_elantra_2022.jpg",
    condition: "Отличное",
    features: ["1 хозяин", "Передний привод", "150 л.с.", "Тонировка", "Расход 7.8 л"],
    description: "Hyundai Elantra CN7 2022. 2.0 150 л.с., 1 хозяин (девушка). Передний привод, отличная шумоизоляция, тонировка вкруг. Средний расход 7.8 л/100 км. В отличном техническом состоянии.",
    bodyType: "седан",
    drive: "передний",
    transmission: "АКПП",
    power: 150,
    seats: 5
  },
  {
    id: 29, brand: "KIA", model: "Optima", year: 2013, color: "Белый",
    mileage: 210000, engine: 2.0, fuel: "бензин", price: 6500000,
    photo: "photos/kia_optima_2013.jpg",
    condition: "Хорошее",
    features: ["Зима/лето", "Полная комплектация"],
    description: "KIA Optima K5 3-го поколения. 2.0 150 л.с. Полная комплектация: панорамная крыша, кожа, климат-контроль. Зима/лето. В хорошем состоянии. Надёжный корейский бизнес-седан.",
    bodyType: "седан",
    drive: "передний",
    transmission: "АКПП",
    power: 150,
    seats: 5
  },
  {
    id: 30, brand: "Hyundai", model: "Elantra", year: 2024, color: "Белый",
    mileage: 40000, engine: 1.5, fuel: "бензин", price: 9200000,
    photo: "photos/hyundai_elantra_1hozain_2024.jpg",
    condition: "Отличное",
    features: ["1 хозяин", "Максимальная комплектация", "100% родной окрас", "Зима/лето"],
    description: "Hyundai Elantra 2024 в максимальной комплектации. 1 хозяин, 100% в родном окрасе. 1.5T 160 л.с. Зима/лето. Apple CarPlay, Android Auto, беспроводная зарядка, вентиляция сидений.",
    bodyType: "седан",
    drive: "передний",
    transmission: "АКПП",
    power: 160,
    seats: 5
  },
  {
    id: 31, brand: "Hyundai", model: "Sonata N-Line", year: 2021, color: "Чёрный",
    mileage: 82000, engine: 2.5, fuel: "бензин", price: 13600000,
    photo: "photos/hyundai_sonata_nline_2021.jpg",
    condition: "Хорошее",
    features: ["N-Line", "2.5 Turbo", "Музыка"],
    description: "Hyundai Sonata в спортивной комплектации N-Line. 2.5T 290 л.с. Спортивная настройка подвески, уникальные N-Line бамперы и решётка. Аудиосистема. Редкая и желанная версия.",
    bodyType: "седан",
    drive: "передний",
    transmission: "АКПП",
    power: 290,
    seats: 5
  },
  {
    id: 32, brand: "Hyundai", model: "Sonata", year: 2023, color: "Белый",
    mileage: 85000, engine: 2.5, fuel: "бензин", price: 15000000,
    photo: "photos/hyundai_sonata_2023.jpg",
    condition: "Хорошее",
    features: ["Камера 360", "Люк", "Электрорегулировка", "100% родной окрас", "ТО имеется"],
    description: "Hyundai Sonata DN8 2023. 2.5 180 л.с. Полная комплектация: камера 360°, люк, электрорегулировка сидений. 100% в родном окрасе. Имеется ТО. Эталон корейского бизнес-класса.",
    bodyType: "седан",
    drive: "передний",
    transmission: "АКПП",
    power: 180,
    seats: 5
  },
  {
    id: 33, brand: "Volkswagen", model: "Polo", year: 2016, color: "Серый",
    mileage: 214000, engine: 1.6, fuel: "бензин", price: 5000000,
    photo: "photos/vw_polo_2016.jpg",
    condition: "Отличное",
    features: ["Дилерский", "Полностью обслужен", "85% родной окрас", "Зима/лето"],
    description: "Volkswagen Polo дилерской сборки. Полностью обслужен, без вложений. 85% в родном окрасе. 1.6 110 л.с. Зима/лето. Немецкое качество и надёжность.",
    bodyType: "седан",
    drive: "передний",
    transmission: "АКПП",
    power: 110,
    seats: 5
  },
  {
    id: 34, brand: "Toyota", model: "Camry", year: 2020, color: "Белый",
    mileage: 105000, engine: 2.5, fuel: "бензин", price: 10500000,
    photo: "photos/toyota_camry_2020.jpg",
    condition: "Хорошее",
    features: ["Полностью обслужена"],
    description: "Toyota Camry XV70 2020. 2.5 181 л.с. Хорошее состояние. Легендарная надёжность и комфорт. Просторный салон, мягкая подвеска. Идеальный вариант для города и трассы.",
    bodyType: "седан",
    drive: "передний",
    transmission: "АКПП",
    power: 181,
    seats: 5
  },
  {
    id: 35, brand: "KIA", model: "Soul", year: 2014, color: "Белый",
    mileage: 160000, engine: 2.0, fuel: "бензин", price: 7300000,
    photo: "photos/kia_soul_2014.jpg",
    condition: "Идеальное техническое состояние",
    features: ["АКПП", "Starline A93", "Зима/лето", "Пуш-старт", "Максимальная комплектация"],
    description: "KIA Soul в максимальной комплектации. 2.0 150 л.с., АКПП. Техническое состояние в идеале, любые проверки. Starline A93, комплект зима/лето, пуш-старт. Бережная эксплуатация.",
    bodyType: "хэтчбек",
    drive: "передний",
    transmission: "АКПП",
    power: 150,
    seats: 5
  },
  {
    id: 36, brand: "KIA", model: "Sportage", year: 2019, color: "Синий",
    mileage: 147000, engine: 2.4, fuel: "бензин", price: 9800000,
    photo: "photos/kia_sportage_2019.jpg",
    condition: "Хорошее",
    features: ["Технически исправен", "Ниже рынка"],
    description: "KIA Sportage 4-го поколения. 2.4 184 л.с. Технически в хорошем состоянии. Цена ниже рынка. Надёжный корейский кроссовер с проверенной репутацией.",
    bodyType: "кроссовер",
    drive: "передний",
    transmission: "АКПП",
    power: 184,
    seats: 5
  },
  {
    id: 37, brand: "KIA", model: "Sportage", year: 2019, color: "Белый",
    mileage: 160000, engine: 2.0, fuel: "бензин", price: 10800000,
    photo: "photos/kia_sportage2_2019.jpg",
    condition: "Отличное",
    features: ["Полный привод", "LED фары", "Starline", "100% родной окрас"],
    description: "KIA Sportage 4-го поколения с полным приводом. 2.0 150 л.с. LED фары, Starline, 100% в родном окрасе. Технически в отличном состоянии. AWD для уверенного движения в любых условиях.",
    bodyType: "кроссовер",
    drive: "полный",
    transmission: "АКПП",
    power: 150,
    seats: 5
  },
  {
    id: 38, brand: "Lexus", model: "LX570", year: 2014, color: "Белый",
    mileage: 199000, engine: 5.7, fuel: "бензин", price: 27700000,
    photo: "photos/lexus_lx570_2014.jpg",
    condition: "Хорошее",
    features: ["Полный привод", "V8 5.7"],
    description: "Легендарный Lexus LX570. V8 5.7 367 л.с. Полный привод с понижающей передачей. Пневмоподвеска, многоступенчатая трансмиссия. Любые дороги покоряются без усилий. Статус и надёжность.",
    bodyType: "внедорожник",
    drive: "полный",
    transmission: "АКПП",
    power: 367,
    seats: 7
  },
  {
    id: 39, brand: "Toyota", model: "Highlander", year: 2011, color: "Серебристый",
    mileage: 213000, engine: 3.5, fuel: "бензин", price: 13000000,
    photo: "photos/toyota_highlander_2011.jpg",
    condition: "Отличное",
    features: ["Европеец", "Starline", "7 мест"],
    description: "Toyota Highlander II европейской сборки. 3.5 273 л.с., 7 мест. Starline сигнализация. Отличное состояние. Надёжный семейный внедорожник японского качества.",
    bodyType: "внедорожник",
    drive: "полный",
    transmission: "АКПП",
    power: 273,
    seats: 7
  },
  {
    id: 40, brand: "Toyota", model: "Highlander", year: 2003, color: "Серый",
    mileage: 240000, engine: 3.3, fuel: "бензин", price: 7300000,
    photo: "photos/toyota_highlander_2003.jpg",
    condition: "Идеальное техническое состояние",
    features: ["5-ступка", "7 мест", "EVA-коврики", "Starline A93", "Полностью обслужена"],
    description: "Toyota Highlander первого поколения. 3.3 224 л.с. Техническое состояние в идеале. 7 мест, АКПП. EVA коврики, Starline A93. Полностью обслужена, бережная эксплуатация.",
    bodyType: "внедорожник",
    drive: "полный",
    transmission: "АКПП",
    power: 224,
    seats: 7
  },
  {
    id: 41, brand: "Toyota", model: "Land Cruiser 200", year: 2007, color: "Белый",
    mileage: null, engine: 4.7, fuel: "бензин", price: 15100000,
    photo: "photos/toyota_lc200_2007.jpg",
    condition: "Хорошее",
    features: ["Зима/лето"],
    description: "Культовый Toyota Land Cruiser 200. 4.7 234 л.с. Полный привод, понижающая передача. Эталон надёжности и проходимости. Служит десятилетиями. Зима/лето.",
    bodyType: "внедорожник",
    drive: "полный",
    transmission: "АКПП",
    power: 234,
    seats: 7
  },
  {
    id: 42, brand: "Lexus", model: "RX300", year: 2018, color: "Чёрный",
    mileage: 79800, engine: 2.0, fuel: "бензин", price: 21800000,
    photo: "photos/lexus_rx300_2018.jpg",
    condition: "Премиум",
    features: ["Турбо", "1 хозяин", "Дилерский", "100% родной окрас", "Датчик слепых зон", "Кожа", "Климат-контроль", "Электропривод багажника", "Полный привод", "Зима/лето"],
    description: "Lexus RX300 Turbo дилерского происхождения. 2.0T 238 л.с. Полный привод, 1 хозяин. 100% в родном окрасе. Полная комплектация: датчик слепых зон, кожа, 2-зонный климат, электропривод багажника. Зима/лето.",
    bodyType: "кроссовер",
    drive: "полный",
    transmission: "АКПП",
    power: 238,
    seats: 5
  },
  {
    id: 43, brand: "Volkswagen", model: "Teramont R-Line", year: 2021, color: "Серый",
    mileage: 18000, engine: 2.4, fuel: "бензин", price: 23200000,
    photo: "photos/vw_teramont_2021.jpg",
    condition: "Отличное",
    features: ["Зима/лето", "Полная комплектация", "R-Line"],
    description: "Volkswagen Teramont R-Line — флагманский кроссовер VW. 2.4T спортивный обвес R-Line. Полная комплектация. Зима/лето. Просторный салон, пневмоподвеска, 7 мест доступны.",
    bodyType: "кроссовер",
    drive: "полный",
    transmission: "АКПП",
    power: 220,
    seats: 7
  },
  {
    id: 44, brand: "Hyundai", model: "Palisade", year: 2020, color: "Серый",
    mileage: 109000, engine: 3.8, fuel: "бензин", price: 16500000,
    photo: "photos/hyundai_palisade_2020.jpg",
    condition: "Предмаксимальная комплектация",
    features: ["Датчик слепых зон", "Проекция на лобовое", "Подогрев/обдув сидений", "8 мест"],
    description: "Hyundai Palisade — флагманский семейный SUV. 3.8 295 л.с. Предмаксимальная комплектация: датчик слепых зон, удержание полосы, проекция на лобовое, подогрев и обдув сидений, 8 мест.",
    bodyType: "внедорожник",
    drive: "передний",
    transmission: "АКПП",
    power: 295,
    seats: 8
  },
  {
    id: 45, brand: "Ford", model: "Explorer", year: 2018, color: "Белый",
    mileage: 115000, engine: 2.3, fuel: "бензин", price: 15700000,
    photo: "photos/ford_explorer_2018.jpg",
    condition: "Максимальная комплектация",
    features: ["Американец", "7 мест", "Полный привод", "1 хозяин в КЗ", "Люк", "Панорама", "100% родной окрас", "Зима/лето"],
    description: "Ford Explorer Ecoboost для корейского рынка. 2.3T 270 л.с. 7 мест, полный привод. 1 хозяин в Казахстане. Максимальная комплектация: люк, панорама, 100% в родном окрасе. Зима/лето.",
    bodyType: "внедорожник",
    drive: "полный",
    transmission: "АКПП",
    power: 270,
    seats: 7
  },
  {
    id: 46, brand: "Lexus", model: "GX460", year: 2010, color: "Белый",
    mileage: 280000, engine: 4.6, fuel: "бензин", price: 14500000,
    photo: "photos/lexus_gx460_2010.jpg",
    condition: "Отличное",
    features: ["Полный привод", "Полностью обслужен", "Зима/лето"],
    description: "Lexus GX460 — внедорожник люкс на базе Land Cruiser Prado. 4.6 V8 296 л.с. Полный привод с пониженной. Полностью обслужен. Зима/лето. Роскошный салон, надёжность проверена временем.",
    bodyType: "внедорожник",
    drive: "полный",
    transmission: "АКПП",
    power: 296,
    seats: 5
  },
  {
    id: 47, brand: "Subaru", model: "Outback", year: 2018, color: "Синий",
    mileage: 178000, engine: 2.5, fuel: "бензин", price: 12300000,
    photo: "photos/subaru_outback_2018.jpg",
    condition: "Отличное",
    features: ["Полный привод", "Boxer-двигатель"],
    description: "Subaru Outback с фирменным симметричным полным приводом AWD. 2.5 Boxer 175 л.с. Отличное состояние. Уникальная система полного привода без доплаты. Высокий клиренс, надёжность Subaru.",
    bodyType: "универсал",
    drive: "полный",
    transmission: "АКПП",
    power: 175,
    seats: 5
  },
  {
    id: 48, brand: "Hyundai", model: "Tucson", year: 2025, color: "Белый",
    mileage: 0, engine: 2.0, fuel: "бензин", price: 15500000,
    photo: "photos/hyundai_tucson_2025.jpg",
    condition: "Новый",
    features: ["Новый", "На гарантии", "Полный привод"],
    description: "Hyundai Tucson 4-го поколения, абсолютно новый. Полный привод, 2.0 150 л.с. На гарантии. Революционный дизайн интерьера и экстерьера. Полный пакет ассистентов безопасности.",
    bodyType: "кроссовер",
    drive: "полный",
    transmission: "АКПП",
    power: 150,
    seats: 5
  },
  {
    id: 49, brand: "Toyota", model: "Land Cruiser 100VX", year: 2005, color: "Чёрный",
    mileage: 469000, engine: 4.7, fuel: "бензин", price: 5700000,
    photo: "photos/toyota_lc100_2005.jpg",
    condition: "Хорошее",
    features: ["Европеец", "Без газа", "Android", "Плавающие сиденья", "Камера заднего вида", "Зима/лето"],
    description: "Toyota Land Cruiser 100 VX европейский. 4.7 V8 235 л.с. Без газа и не было. Android мультимедиа, память сидений, плавающие сиденья, камера заднего вида. Зима/лето. Культовая надёжность.",
    bodyType: "внедорожник",
    drive: "полный",
    transmission: "АКПП",
    power: 235,
    seats: 8
  },
  {
    id: 50, brand: "Jetour", model: "X70", year: 2023, color: "Серый",
    mileage: 16650, engine: 1.5, fuel: "бензин", price: 8100000,
    photo: "photos/jetour_x70_2023.jpg",
    condition: "Дилерский, на гарантии",
    features: ["7 мест", "Дилерский", "На гарантии", "Расход 8 л"],
    description: "Jetour X70 — современный китайский 7-местный кроссовер. 1.5T 156 л.с. Дилерский, ещё на гарантии. 7 мест. Средний расход 8/8.2 л. Просторный салон, богатая комплектация.",
    bodyType: "кроссовер",
    drive: "передний",
    transmission: "АКПП",
    power: 156,
    seats: 7
  },
  {
    id: 51, brand: "Mercedes-Benz", model: "G320", year: 1996, color: "Серый",
    mileage: 170000, engine: 3.2, fuel: "бензин", price: 9500000,
    photo: "photos/mercedes_g320_1996.jpg",
    condition: "Хорошее, без вложений",
    features: ["Полный привод", "Классика", "G-класс"],
    description: "Легендарный Mercedes-Benz G-класс (G320). 3.2 V6 210 л.с. Полный привод с тремя блокировками. Без вложений. Икона внедорожного стиля, строился для армии — покорит всё.",
    bodyType: "внедорожник",
    drive: "полный",
    transmission: "АКПП",
    power: 210,
    seats: 5
  },
  {
    id: 52, brand: "Toyota", model: "Camry (газ-бензин)", year: 2014, color: "Чёрный",
    mileage: 213000, engine: 2.5, fuel: "газ-бензин", price: 11500000,
    photo: "photos/toyota_camry_2014.jpg",
    condition: "Отличное техническое состояние",
    features: ["Газ-бензин", "Максимальная Navi комплектация", "Бронепленка люкс", "Все стекла родные", "Два ключа", "Зима/лето", "GSM автозапуск"],
    description: "Toyota Camry XV55 в максимальной Navi комплектации. Газ-бензин ГБО. Бронепленка люкс пакет. Все стёкла родные включая лобовое. Два ключа. GSM сигнализация с автозапуском. Зима/лето.",
    bodyType: "седан",
    drive: "передний",
    transmission: "АКПП",
    power: 181,
    seats: 5
  },
  {
    id: 53, brand: "Lada", model: "Vesta Cross", year: 2018, color: "Коричневый",
    mileage: 150000, engine: 1.6, fuel: "бензин", price: 5000000,
    photo: "photos/lada_vesta_cross_2018.jpg",
    condition: "Хорошее",
    features: ["В родне", "Зима/лето"],
    description: "Lada Vesta Cross — приподнятая версия популярной Весты. 1.6 106 л.с. В родном окрасе. Зима/лето. Увеличенный клиренс, защита картера. Бюджетный и практичный выбор.",
    bodyType: "кроссовер",
    drive: "передний",
    transmission: "МКПП",
    power: 106,
    seats: 5
  },
  {
    id: 54, brand: "Hyundai", model: "Accent", year: 2013, color: "Белый",
    mileage: 320000, engine: 1.6, fuel: "бензин", price: 4500000,
    photo: "photos/hyundai_accent_2013.jpg",
    condition: "Хорошее",
    features: ["Аудиосистема", "Усилитель", "85% родной окрас", "АКПП", "Зима/лето"],
    description: "Hyundai Accent (Solaris) — народный автомобиль. 1.6 123 л.с. Аудиосистема с усилителем. 85% в родном окрасе. АКПП. Зима/лето. Техническое состояние хорошее.",
    bodyType: "седан",
    drive: "передний",
    transmission: "АКПП",
    power: 123,
    seats: 5
  },
  {
    id: 55, brand: "Hyundai", model: "Solaris", year: 2015, color: "Серый",
    mileage: 155000, engine: 1.6, fuel: "бензин", price: 3800000,
    photo: "photos/hyundai_solaris_2015.jpg",
    condition: "Хорошее",
    features: ["Передний привод", "Ходовка и мотор без вложений"],
    description: "Hyundai Solaris — хит продаж среди бюджетных авто. 1.6 123 л.с. Передний привод. Ходовка и мотор без вложений. Технически в хорошем состоянии. Надёжный и экономичный выбор.",
    bodyType: "седан",
    drive: "передний",
    transmission: "АКПП",
    power: 123,
    seats: 5
  },
  {
    id: 56, brand: "Volkswagen", model: "Multivan T4", year: 1997, color: "Красный",
    mileage: 102000, engine: 2.8, fuel: "бензин", price: 5700000,
    photo: "photos/vw_multivan_t4_1997.jpg",
    condition: "Идеальное",
    features: ["Двигатель VR6 от Audi", "Новая коробка", "Люк", "Автозапуск", "Автономка", "Свежий окрас"],
    description: "Volkswagen Multivan T4 — культовый микроавтобус. Установлен мощный VR6 от Audi. Новая коробка. Свежий окрас, биглиды, люк, автозапуск, автономный отопитель. Идеальное состояние.",
    bodyType: "минивэн",
    drive: "задний",
    transmission: "АКПП",
    power: 174,
    seats: 7
  },
  {
    id: 57, brand: "Toyota", model: "RAV-4", year: 2011, color: "Чёрный",
    mileage: 200000, engine: 2.0, fuel: "бензин", price: 7800000,
    photo: "photos/toyota_rav4_2011.jpg",
    condition: "Хорошее",
    features: ["1 владелец", "Без вложений"],
    description: "Toyota RAV4 третьего поколения. 2.0 147 л.с. 1 владелец, вложений не требует. Надёжный японский кроссовер с безупречной репутацией. Экономичный и практичный.",
    bodyType: "кроссовер",
    drive: "полный",
    transmission: "АКПП",
    power: 147,
    seats: 5
  },
  {
    id: 58, brand: "Mitsubishi", model: "Outlander", year: 2008, color: "Чёрный",
    mileage: null, engine: 2.4, fuel: "бензин", price: 5800000,
    photo: "photos/mitsubishi_outlander_2008.jpg",
    condition: "Хорошее",
    features: ["100% родной окрас", "АКПП", "Два ключа", "Starline автозапуск", "Без вложений"],
    description: "Mitsubishi Outlander 2-го поколения. 2.4 170 л.с. 100% родной окрас, родные стёкла включая лобовое. Два ключа, Starline с автозапуском. Коробка и двигатель 10/10. Без вложений.",
    bodyType: "кроссовер",
    drive: "полный",
    transmission: "АКПП",
    power: 170,
    seats: 5
  },
  {
    id: 59, brand: "Renault", model: "Sandero", year: 2015, color: "Серый",
    mileage: 186000, engine: 1.6, fuel: "бензин", price: 5000000,
    photo: "photos/renault_sandero_2015.jpg",
    condition: "Хорошее",
    features: ["Без вложений", "95% родной окрас"],
    description: "Renault Sandero — надёжный бюджетный хэтчбек. 1.6 82 л.с. В хорошем состоянии, без вложений. 95% в родном окрасе. Отличный первый автомобиль или семейный городской вариант.",
    bodyType: "хэтчбек",
    drive: "передний",
    transmission: "АКПП",
    power: 82,
    seats: 5
  },
  {
    id: 60, brand: "Subaru", model: "XV", year: 2012, color: "Белый",
    mileage: 193000, engine: 2.0, fuel: "бензин", price: 5900000,
    photo: "photos/subaru_xv_2012.jpg",
    condition: "Хорошее",
    features: ["Полный привод", "Шумоизоляция"],
    description: "Subaru XV с фирменным симметричным AWD. 2.0 150 л.с. Шумоизоляция. Высокий клиренс 200 мм. Надёжный Boxer-двигатель. Уникальный характер Subaru в городском кузове.",
    bodyType: "кроссовер",
    drive: "полный",
    transmission: "АКПП",
    power: 150,
    seats: 5
  },
  {
    id: 61, brand: "Toyota", model: "Corolla Verso", year: 2007, color: "Синий",
    mileage: 400000, engine: 1.6, fuel: "газ-бензин", price: 3000000,
    photo: "photos/toyota_corolla_verso_2007.jpg",
    condition: "Хорошее техническое",
    features: ["Газ-бензин", "МКПП", "Starline", "Зима"],
    description: "Toyota Corolla Verso — надёжный семейный минивэн. 1.6 газ-бензин. Механика. В хорошем техническом состоянии. Экономичный, практичный, Starline. Зима. Идеален для большой семьи.",
    bodyType: "минивэн",
    drive: "передний",
    transmission: "МКПП",
    power: 110,
    seats: 7
  },
  {
    id: 62, brand: "Ford", model: "Fiesta", year: 2010, color: "Белый",
    mileage: null, engine: 1.4, fuel: "бензин", price: 3100000,
    photo: "photos/ford_fiesta_2010.jpg",
    condition: "Хорошее",
    features: ["Новые тормоза", "Новые диски", "Ходовка без вложений"],
    description: "Ford Fiesta 6-го поколения — компактный городской хэтчбек. 1.4 96 л.с. Заменены передние тормозные колодки, новые диски, ручник. Ходовка без вложений. По желанию кузов.",
    bodyType: "хэтчбек",
    drive: "передний",
    transmission: "МКПП",
    power: 96,
    seats: 5
  },
  {
    id: 63, brand: "Suzuki", model: "Grand Vitara", year: 2008, color: "Серебристый",
    mileage: 135000, engine: 2.7, fuel: "бензин", price: 7000000,
    photo: "photos/suzuki_grand_vitara_2008.jpg",
    condition: "Хорошее",
    features: ["Зимние шины", "Видеорегистратор", "Контрактный двигатель"],
    description: "Suzuki Grand Vitara с полным приводом. 2.7 185 л.с. Зимние шины, видеорегистратор. Контрактный двигатель. Компактный, манёвренный и надёжный внедорожник для города и бездорожья.",
    bodyType: "внедорожник",
    drive: "полный",
    transmission: "АКПП",
    power: 185,
    seats: 5
  },
  {
    id: 64, brand: "Toyota", model: "Avensis", year: 2006, color: "Белый",
    mileage: null, engine: 1.8, fuel: "бензин", price: 4500000,
    photo: "photos/toyota_avensis_2006.jpg",
    condition: "Хорошее",
    features: ["Надёжный"],
    description: "Toyota Avensis — европейский седан с японской надёжностью. 1.8 129 л.с. В хорошем состоянии. Классический дизайн, просторный салон. Один из самых надёжных автомобилей своего класса.",
    bodyType: "седан",
    drive: "передний",
    transmission: "АКПП",
    power: 129,
    seats: 5
  }
];
